# Generated by Django 5.2.6 on 2025-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FileField(default=1, upload_to='movie_image/'),
            preserve_default=False,
        ),
    ]
