# Generated by Django 5.2.6 on 2025-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateField(),
        ),
    ]
